### ISSUE TITLE
Add placeholder image for cafes that don't have an image

### ISSUE THREAD

**Issue by antalindisguise** [thirdwavelist/thirdwavelist-web#12]

**Comment by anthonymonori** [comment]
![simson-petrol-193261-unsplash 1](https://user-images.githubusercontent.com/935897/39208404-2e3461f2-4803-11e8-9775-5efb134f6ffd.jpg)
![mac-glassford-99924-unsplash 1](https://user-images.githubusercontent.com/935897/39208405-2e50a380-4803-11e8-9542-9448dc8ef42a.jpg)
![bogdan-dada-279935-unsplash 1](https://user-images.githubusercontent.com/935897/39208406-2e6b00b8-4803-11e8-9a95-5f9ce909d454.jpg)

**Comment by antalindisguise** [comment]
This was already done.
